### ISSUE TITLE
Comment regarding rm -rf in execution scripts

### ISSUE THREAD

**Issue by LostAccount** [bkuhlmann/mac_os-config#2]
Hi

Thank you for putting this together, it's definitely interesting stuff.

In the spirit of ensuring data loss is avoided at all costs, could the executable script, "apply_basic_settings" include a strong warning to ensure users do not lose data when running the script. Does it include a y/N response to go on or does the rm -rf execute without warning the user?

**snippet from $HOME/mac_os_config/bin/apply_basic_settings**
```
printf "Cleaning default directories...\n"
rm -rf $HOME/Documents/*
rm -rf $HOME/Downloads/* 
```

I believe the script or the README.md should include warnings that help prevent potential data loss.

Kindest regards
—Alex

**Comment by bkuhlmann** [comment]
Thanks. Yeah, I'll add that in. These scripts were intended for newly formatted machines so that idea was that you wouldn't have any data to be lost. Plus, less prompts means faster install and less baby sitting (as a full run of these scripts takes just under an hour to setup a new machine). That said, destructive actions should have warnings.

**Comment by bkuhlmann** [comment]
This issues is fixed in this [commit](https://github.com/bkuhlmann/mac_os-config/commit/c8b469731bba). I'll be releasing this change in the next major version release (as soon as additional Homebrew Cask support is added).
