### ISSUE TITLE
Consider adding force flag

### ISSUE THREAD

**Issue by Austin1** [bkuhlmann/mac_os-config#5]
Trying out your scripts for the first time and noticed I kept getting an error on the app store installs. You wouldn’t get this issue because I’m sure at some point you’ve manually installed all the apps in your app store file, but if you have never installed the app before, it will fail with an error “Redownload Unavailable with This Apple Account"
![image](https://github.com/user-attachments/assets/86d30b20-6663-443b-ae39-fe1a0c059428)

After taking a look at the [mas documentation](https://github.com/mas-cli/mas), I think the following may need to be different:

1. Change [this](https://github.com/bkuhlmann/mac_os-config/blob/78e3a6742aec51b027ff6633ee2ff649c05c9eb3/bin/install_app_store#L6)
```
# Acorn
mas install 1547371478
```
to
```
# Acorn
mas purchase 1547371478
```

**Comment by bkuhlmann** [comment]
Hey Austin, thanks. So running `purchase` results in the following when already installed:

``` 
mas purchase 1547371478
Warning: Acorn has already been purchased.
```

Also, `purchase` only works for free apps. In the case of Acorn, it's a paid app so even `purchase` wouldn't work for that.

All of this said, this project is meant to show how I use the [macOS](https://alchemists.io/projects/mac_os) project so you have a blueprint on how to customize and tweak for your needs. At best, I think the documentation could be updated to make this more clear? The other option -- for your use case -- would be to skip the App Store install step or, even better, change to what apps you like to use.

**Comment by bkuhlmann** [comment]
I ended up adding the following clarification to the [App Store](https://alchemists.io/projects/mac_os-config#_app_store) documentation:

> Installs [App Store](https://www.apple.com/app-store) applications as managed by the [Mac App Store](https://github.com/mas-cli/mas) CLI which assumes you’ve purchased the applications listed below:

I suppose, in the future, one could argue that conditional logic be added to check if an app is installed or needs to be purchased but since these scripts are meant to be simple where each line in the script is a new install that seems a bit overkill at the moment.

I'm going to close this for now (or until more people find that they want this conditional behavior).
